### ISSUE TITLE
column head individual search not working (also on version django>2 and mysql_5.7

### ISSUE THREAD

**Issue by chainwang31** [twtrubiks/DRF-dataTable-Example-server-side#4]
Hi, the column head individual search is not working and also not working on the django>2 and mysql_5.7 version (I made some edits to that with column search).

Any ideas? Thank you,

您好，我发现这个版本以及django>2 and mysql_5.7版本(加上列搜索功能后)的列单独搜索都不能使用。

**Comment by alan6666-erp** [comment]
@chainwang31 Do you mean the search function? I just tested it, it is normal, can you explain it clearly?

**Comment by twtrubiks** [comment]
Hi @chainwang31 
Do you mean the search function? I just tested it, it is normal, can you explain it clearly?

**Comment by chainwang31** [comment]
Hi twtrubiks,
I meant the column individual search function (overall search box works fine). I added column search per "https://datatables.net/reference/api/columns().search()", as code below, but it doesn't work.

index.js:
$('#datatables thead th').each( function () {
    var title = $('#datatables thead th').eq( $(this).index() ).text();
    $(this).html( '<input type="text" placeholder="Search '+title+'" />' );
} );

// Apply the filter
table.columns().every( function () {
    var column = this;

    $( 'input', this.header() ).on( 'keyup change', function () {
        column
            .search( this.value )
            .draw();
    } );
} );

**Comment by twtrubiks** [comment]
Hi @chainwang31 
I am not very familiar with the part of JavaScript (I am more focused on the back end), may have to trouble you to study on your own.

**Comment by chainwang31** [comment]
Thanks for your support:)
